# Generated by Django 3.0.6 on 2020-05-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_api', '0002_maradmin_body_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='maradmin',
            name='body',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
